# Generated by Django 5.2.7 on 2025-10-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
