# Generated by Django 5.2.7 on 2025-10-29 16:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_last_update_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال پردازش'), ('Shipped', 'ارسال شده به پست'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=50),
        ),
    ]
