# Generated by Django 5.2.7 on 2025-10-22 21:19

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 10, 23, 0, 49, 47, 383845)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address1', models.CharField(blank=True, max_length=2000)),
                ('address2', models.CharField(blank=True, max_length=2000)),
                ('city', models.CharField(blank=True, max_length=2000)),
                ('state', models.CharField(blank=True, max_length=2000)),
                ('zipcode', models.CharField(blank=True, max_length=2000)),
                ('country', models.CharField(default='IRAN', max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
